{"uuid": "ffe7e3dd-4fd0-4bd0-bc81-7503e2d7f8c4", "children": ["18b5cde3-7954-4e60-b0ce-a88f8fa7277b"], "befores": [{"name": "get_access_token", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth.example.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001E36F3FA4D0>: Failed to resolve 'oauth.example.com' ([Errno 11001] getaddrinfo failed)\"))\n", "trace": "  File \"D:\\PythonTutorial\\PythonApiAutomation\\.env\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PythonTutorial\\PythonApiAutomation\\.env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PythonTutorial\\PythonApiAutomation\\.env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PythonTutorial\\PythonApiAutomation\\restApiRequests\\test_0Auth_api.py\", line 19, in get_access_token\n  File \"D:\\PythonTutorial\\PythonApiAutomation\\.env\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PythonTutorial\\PythonApiAutomation\\.env\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PythonTutorial\\PythonApiAutomation\\.env\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PythonTutorial\\PythonApiAutomation\\.env\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PythonTutorial\\PythonApiAutomation\\.env\\Lib\\site-packages\\requests\\adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1693915328733, "stop": 1693915328776}], "start": 1693915328733, "stop": 1693915328913}